export interface Recipe {
  id: string;
  title: string;
  image: string;
  cookTime: number;
  servings: number;
  rating: number;
  cuisine: string;
  allergens: string[];
  ingredients: Array<{ name: string; quantity: string; unit: string }>;
  steps: string[];
  nutrition: {
    calories: number;
    protein: number;
    carbs: number;
    fats: number;
  };
  author: string;
  youtubeUrl?: string;
}

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    title: "Creamy Tomato Basil Pasta",
    image: "recipe-1",
    cookTime: 25,
    servings: 4,
    rating: 4.8,
    cuisine: "Italian",
    allergens: ["Gluten", "Dairy"],
    ingredients: [
      { name: "Pasta", quantity: "400", unit: "g" },
      { name: "Cherry tomatoes", quantity: "300", unit: "g" },
      { name: "Fresh basil", quantity: "1", unit: "bunch" },
      { name: "Garlic", quantity: "4", unit: "cloves" },
      { name: "Heavy cream", quantity: "200", unit: "ml" },
      { name: "Parmesan cheese", quantity: "100", unit: "g" },
      { name: "Olive oil", quantity: "3", unit: "tbsp" },
    ],
    steps: [
      "Boil pasta according to package instructions until al dente",
      "Heat olive oil in a large pan over medium heat",
      "Sauté minced garlic for 1 minute until fragrant",
      "Add halved cherry tomatoes and cook for 5-7 minutes",
      "Pour in heavy cream and simmer for 3 minutes",
      "Drain pasta and add to the sauce",
      "Toss with torn basil leaves and grated parmesan",
      "Season with salt and pepper to taste",
    ],
    nutrition: { calories: 520, protein: 18, carbs: 65, fats: 22 },
    author: "Generated by AI",
    youtubeUrl: "https://youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "2",
    title: "Colorful Veggie Stir-Fry",
    image: "recipe-2",
    cookTime: 15,
    servings: 3,
    rating: 4.6,
    cuisine: "Asian",
    allergens: ["Soy"],
    ingredients: [
      { name: "Bell peppers", quantity: "2", unit: "pcs" },
      { name: "Broccoli", quantity: "200", unit: "g" },
      { name: "Carrots", quantity: "2", unit: "pcs" },
      { name: "Snap peas", quantity: "150", unit: "g" },
      { name: "Soy sauce", quantity: "3", unit: "tbsp" },
      { name: "Ginger", quantity: "1", unit: "inch" },
      { name: "Sesame oil", quantity: "2", unit: "tbsp" },
    ],
    steps: [
      "Cut all vegetables into bite-sized pieces",
      "Heat sesame oil in a wok over high heat",
      "Add grated ginger and stir for 30 seconds",
      "Add harder vegetables (carrots, broccoli) first",
      "Stir-fry for 3-4 minutes",
      "Add bell peppers and snap peas",
      "Cook for another 2-3 minutes",
      "Add soy sauce and toss well",
    ],
    nutrition: { calories: 180, protein: 8, carbs: 24, fats: 8 },
    author: "Generated by AI",
  },
  {
    id: "3",
    title: "Rainbow Quinoa Power Bowl",
    image: "recipe-3",
    cookTime: 30,
    servings: 2,
    rating: 4.9,
    cuisine: "Mediterranean",
    allergens: [],
    ingredients: [
      { name: "Quinoa", quantity: "200", unit: "g" },
      { name: "Avocado", quantity: "1", unit: "pc" },
      { name: "Cherry tomatoes", quantity: "150", unit: "g" },
      { name: "Cucumber", quantity: "1", unit: "pc" },
      { name: "Chickpeas", quantity: "200", unit: "g" },
      { name: "Lemon", quantity: "1", unit: "pc" },
      { name: "Olive oil", quantity: "3", unit: "tbsp" },
    ],
    steps: [
      "Rinse quinoa and cook according to package instructions",
      "Drain and rinse chickpeas",
      "Dice cucumber, tomatoes, and avocado",
      "Mix olive oil, lemon juice, salt, and pepper for dressing",
      "In a bowl, layer cooked quinoa",
      "Arrange vegetables and chickpeas on top",
      "Drizzle with dressing",
      "Garnish with fresh herbs if desired",
    ],
    nutrition: { calories: 420, protein: 15, carbs: 52, fats: 18 },
    author: "Generated by AI",
  },
];
